#!/bin/bash

sudo docker.io run -i -t --name d-apache2php55 \
-p 80:80 \
-v /var/www/html:/App/html \
-v /abi_store/apps/apache2/sites:/App/apache2.conf \
-v /abi_store/apps/apache2/log:/App/apache2.conf \
--link a-mysql:a-mysql --link a-mongo:a-mongo \
abilashgt/apache2php55 /bin/bash
